### ISSUE TITLE
Feature Request: Piano Roll below the frequency scale

### ISSUE THREAD

**Issue by MrBollie** [x42/fil4.lv2#12]
Hey there! :)

It would be nice to have a piano roll below the frequency scale and tinting the aproximate keys corresponding to the set band frequency accordingly. 

This would be very convenient if you communicate in more musical terms. Like, "Whenever I hit my low E on my Bass, I have this resonant frequency." ;)

Cheers
Bollie

**Comment by x42** [comment]
Nice idea! I've started some experiments. Perhaps an annotation "Note +/- cent" is more useful.

A piano-roll is kinda hard to read and I don't yet know where to draw it.

The screenshot piano-roll below shows MIDI notes 21..128). It looks kinda odd to cut it off at 12.5kHz (note 127). Also Pianos don't even go that high.

![Screenshot at 2019-08-15 03-42-08](https://user-images.githubusercontent.com/30246/63067378-002eea00-bf0f-11e9-9eb2-fc5dc579dc15.png)

**Comment by x42** [comment]
Perhaps showing "_Note Octave cents_" below the frequency dial at the bottom or as tooltip on the knob, is most useful.

What do you think?

**Comment by x42** [comment]
4fd4cb175 now looks like

![Screenshot at 2019-08-15 06-25-08](https://user-images.githubusercontent.com/30246/63072770-e220b400-bf25-11e9-8fb6-79730493ad0b.png)

**Comment by nettings** [comment]
If you go with the piano (not "roll", just the keyboard) metaphor, then don't extend it to the entire spectrum, just from A,, to a´´´´, so that it actually provides some "recognition factor" for musicians.
I like it.

**Comment by x42** [comment]
Good idea. That indeed increases readability. Notes outside the A0..C8 range are now shaded:

![Screenshot at 2019-08-15 16-08-42](https://user-images.githubusercontent.com/30246/63100313-1b354480-bf77-11e9-8044-5dd643959275.png)

**Comment by x42** [comment]
Feature complete as of  v0.6.6-10 8770e99

Now with snap + drag support of the indicators on the piano[roll], and configurable tuning (scroll-wheel on the "A:440" indicator left of the piano).

Please test.

**Comment by thenktor** [comment]
Would be nice to make the piano roll optional ;-)
