### ISSUE TITLE
feature request: larger ranges for the q of the shelves and filters

### ISSUE THREAD

**Issue by magnetophon** [x42/fil4.lv2#21]
In [EQ10Q](http://eq10q.sourceforge.net/), you can use the HP, LP and shelving filters with extremely high and low resonances, which is often useful.

**Comment by x42** [comment]
the HP/LP are different filters which are modeled to match analog equivalent gain and zero phase shift at nyquist.

They are not comparable with the standard biqad filters found in textbook EQs. If you need a steep cutoff you have to accept audible trade-offs which I'm not prepared to make with this EQ.
