### ISSUE TITLE
Feature request: all bands full frequency range

### ISSUE THREAD

**Issue by magnetophon** [x42/fil4.lv2#24]
Sometimes you really do want a HP at 15kHz, for example.
Also: sometimes you want to use all bell filters in the same frequency range.

Limited ranges are great if that is the only way you can get a precise setting, but in the plugin worls you can just CTRL-drag or even type in a value.

**Comment by x42** [comment]
Defiantly not going to happen. This is a dedicated limitation, carefully chosen to speed up mixing.
