### ISSUE TITLE
replace robtk url from git:// to https://

### ISSUE THREAD

**Issue by ycollet** [x42/fil4.lv2#27]
It looks like the git:// if no more supported by github. So, cloning the robtk submodule hangs. Can you replace the url of the submodule from git:// to https:// ?

**Comment by x42** [comment]
This was already done in 3755adadfcb1.

If you have an existing clone, you have run `git submodule sync` to update any existing remote URL

**Comment by ycollet** [comment]
OK, thanks !
I clone the last release, that's why I've got the git:// ...
