### ISSUE TITLE
Feature request: install destination for Fedora x86_64

### ISSUE THREAD

**Issue by lorenzosu** [x42/fil4.lv2#9]
Hi,
On Fedora 24 x86_64 I had to manually change the Makefile with:

$(PREFIX)/lib64/lv2

Then do the make install PREFIX=/usr
to have it installed in /usr/lib64/lv2 (default for Fedora x86_64)

Not sure if there's a way to support this directly?

Thanks.

**Comment by x42** [comment]
Please see http://lv2plug.in/pages/filesystem-hierarchy-standard.html and nudge fedora (LV2 PATH is not arch dependent).

if you really need to, you can run  `make LV2DIR=/your/nonstandard/lv2/path` (there's no need to change the makefile, all the variables can be overridden with either environment variables or make command arguments).

**Comment by lorenzosu** [comment]
Thanks for the info.
Lorenzo.

**Comment by x42** [comment]
Oops. I meant  `make install LV2DIR=/usr/lib64/lv2 PREFIX=/usr/  install`  (there's no configure step, parameters need to be given for the install step)

That' puts the the jack binary in `/usr/bin/` and the LV2 plugin  in `/usr/lib64/lv2`

The makefile follows the established gnu/make variables (BINDIR, PREFIX, DESTDIR, ...) in case you need to further customize things.
